name: chat_message_ui_example
description: Demonstrates all features of the chat_message_ui package.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chat_message_ui:
    path: ../
  smart_pagination: ^3.1.1
  intl: ^0.20.1
  firebase_core: ^3.15.2
  http: ^1.2.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  file_picker: ^10.3.8
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.20.1
  http: ^1.2.2

flutter:
  uses-material-design: true
