name: chat_message_ui
publish_to: 'none'
description: A comprehensive, unified Chat UI library for displaying and interacting with chat messages. Platform-agnostic interface supporting multiple data sources.
version: 1.0.0
homepage: https://github.com/geniussystems24/chat_message_ui

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: any
  url_launcher: any
  intl: any
  text_preview:
    path: ../text_preview
  lottie: any
  record: any
  logger: any
  recase: any
  collection: any
  flutter_animate: any
  font_awesome_flutter: any
  link_preview_generator: any
  just_audio: ^0.10.5
  chewie: any
  video_player: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
