name: chat_message_ui
publish_to: "none"
description: A comprehensive, unified Chat UI library for displaying and
  interacting with chat messages. Platform-agnostic interface supporting
  multiple data sources.
version: 1.4.0
homepage: https://github.com/geniussystems24/chat_message_ui

resolution: workspace
environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  cached_network_image: ^3.4.1
  chewie: ^1.13.0
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^10.12.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  logger: ^2.6.2
  lottie: ^3.1.3
  recase: ^4.1.0
  record: ^6.1.2
  smart_pagination: ^3.1.1
  super_interactive_text: ^1.1.0
  transfer_kit: ^2.1.0+1
  url_launcher: ^6.3.2
  video_player: ^2.10.1
  link_preview_generator: ^1.2.0
  tooltip_card: ^2.6.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter